#!/usr/bin/env node

/**
 * ABI Sync Script
 * Automatically extracts ABIs from Foundry build artifacts and updates frontend contract files
 */

const fs = require('fs');
const path = require('path');

const GREEN = '\x1b[32m';
const BLUE = '\x1b[34m';
const YELLOW = '\x1b[33m';
const RED = '\x1b[31m';
const RESET = '\x1b[0m';

// Contract mapping: contract name -> output path
const CONTRACTS = {
  'RegistryV2': {
    artifact: 'contracts/out/RegistryV2.sol/RegistryV2.json',
    output: 'src/lib/abis/RegistryV2.json',
    envVar: 'VITE_REGISTRY_ADDRESS'
  },
  'MintingController': {
    artifact: 'contracts/out/MintingController.sol/MintingController.json',
    output: 'src/lib/abis/MintingController.json',
    envVar: 'VITE_MINTING_CONTROLLER_ADDRESS'
  },
  'Treasury': {
    artifact: 'contracts/out/Treasury.sol/Treasury.json',
    output: 'src/lib/abis/Treasury.json',
    envVar: 'VITE_TREASURY_ADDRESS'
  },
  'SARCToken': {
    artifact: 'contracts/out/SARCToken.sol/SARCToken.json',
    output: 'src/lib/abis/SARCToken.json',
    envVar: 'VITE_SARC_TOKEN_ADDRESS'
  }
};

console.log(`${BLUE}🔄 Syncing contract ABIs...${RESET}\n`);

// Create ABIs directory if it doesn't exist
const abisDir = path.join(process.cwd(), 'src/lib/abis');
if (!fs.existsSync(abisDir)) {
  fs.mkdirSync(abisDir, { recursive: true });
  console.log(`${GREEN}✓${RESET} Created ABIs directory`);
}

let successCount = 0;
let errorCount = 0;

// Process each contract
for (const [name, config] of Object.entries(CONTRACTS)) {
  const artifactPath = path.join(process.cwd(), config.artifact);
  const outputPath = path.join(process.cwd(), config.output);
  
  try {
    if (!fs.existsSync(artifactPath)) {
      console.log(`${YELLOW}⚠${RESET} Skipping ${name}: artifact not found (run forge build first)`);
      continue;
    }
    
    // Read the Foundry artifact
    const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
    
    // Extract just the ABI
    const abi = artifact.abi;
    
    if (!abi || abi.length === 0) {
      console.log(`${RED}✗${RESET} ${name}: Empty ABI`);
      errorCount++;
      continue;
    }
    
    // Write ABI to output file
    fs.writeFileSync(outputPath, JSON.stringify(abi, null, 2));
    
    console.log(`${GREEN}✓${RESET} Synced ${name} (${abi.length} functions/events)`);
    successCount++;
    
  } catch (error) {
    console.log(`${RED}✗${RESET} ${name}: ${error.message}`);
    errorCount++;
  }
}

// Generate TypeScript index file for easy imports
const indexContent = `// Auto-generated by sync-abis.js - Do not edit manually

${Object.entries(CONTRACTS).map(([name, config]) => 
  `import ${name}ABI from './${path.basename(config.output)}';\n`
).join('')}

export {
${Object.keys(CONTRACTS).map(name => `  ${name}ABI`).join(',\n')}
};
`;

fs.writeFileSync(path.join(abisDir, 'index.ts'), indexContent);
console.log(`${GREEN}✓${RESET} Generated index.ts`);

console.log(`\n${BLUE}Summary:${RESET} ${successCount} synced, ${errorCount} errors`);

if (successCount > 0) {
  console.log(`\n${GREEN}✅ ABIs synced successfully!${RESET}`);
  console.log(`${BLUE}💡 Tip:${RESET} Import ABIs from 'src/lib/abis' instead of defining them inline`);
  process.exit(0);
} else {
  console.log(`\n${RED}❌ No ABIs were synced${RESET}`);
  process.exit(1);
}
