// Auto-generated by sync-abis.js - Do not edit manually

import RegistryV2ABI from './RegistryV2.json';
import MintingControllerABI from './MintingController.json';
import TreasuryABI from './Treasury.json';
import SARCTokenABI from './SARCToken.json';


export {
  RegistryV2ABI,
  MintingControllerABI,
  TreasuryABI,
  SARCTokenABI
};
